/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menukaryawan;


import pembukuanumkm.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class DataBarangKaryawan extends javax.swing.JFrame {
    
      public void kode_barangg() {
        try {
            String sql = "SELECT id_bahan FROM data_bmentah order by id_bahan desc";
            Connection conn = (Connection) Koneksi.koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            if (rs.next()) {
                String Idno = rs.getString("id_bahan").substring(2);
                String AN = "" + (Integer.parseInt(Idno) + 1);
                String Nol = "";
                if (AN.length() == 1) {
                    Nol = "0";
                } else if (AN.length() == 2) {
                    Nol = "";
               
              
                }

                txtKBarang.setText("BM" + Nol + AN);
            } else {
                txtKBarang.setText("BM01");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
 public void loadtable() {
        DefaultTableModel tbl = new DefaultTableModel();
      
        tbl.addColumn("id bahan");
        tbl.addColumn("nama bahan");
        tbl.addColumn("stok bahan");
      
        loadtable.setModel(tbl);

        try {

            java.sql.Statement statement = Koneksi.koneksi.getKoneksi().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM data_bmentah");

            while (res.next()) {
                tbl.addRow(new Object[]{
                    
                    res.getString("id_bahan"),
                    res.getString("nama_bahan"),
                    res.getString("stok_bahan")
                });
                loadtable.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Salah");
        }

    }
    /**
     * Creates new form DataBarangKaryawan
     */
  private void showData() {
        try {
            String kode_barang = loadtable.getValueAt(this.loadtable.getSelectedRow(), 0).toString();
            Connection conn = (Connection) Koneksi.koneksi.getKoneksi();
            Statement s = conn.createStatement();
            ResultSet r = s.executeQuery("SELECT id_bahan, nama_bahan ,stok_bahan FROM data_bmentah WHERE id_bahan = '" + kode_barang + "'");
            if (r.next()) {
                
               this.txtKBarang.setText(r.getString("id_bahan"));
                this.txtNBarang.setText(r.getString("nama_bahan"));
                this.txtSBarang.setText(r.getString("stok_bahan"));
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }

    public DataBarangKaryawan() {
        initComponents();
        loadtable();
        kode_barangg();
        ImageIcon icon = new ImageIcon("C:\\Users\\laptophp\\Downloads\\CIRCLE.png");
this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loadtable = new javax.swing.JTable();
        txtKBarang = new javax.swing.JTextField();
        txtNBarang = new javax.swing.JTextField();
        backtomenu = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        refreshs = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnLapBMasuk = new javax.swing.JButton();
        btnTPembelian = new javax.swing.JButton();
        btnLapBKeluar = new javax.swing.JButton();
        btnDataKaryawan = new javax.swing.JButton();
        btnTPenjualan = new javax.swing.JButton();
        txtSBarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1378, 767));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadtable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Stok Barang", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        loadtable.setToolTipText("");
        loadtable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        loadtable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadtable.setRowHeight(30);
        loadtable.setRowMargin(2);
        loadtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(loadtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 880, 310));

        txtKBarang.setEditable(false);
        txtKBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtKBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtKBarang.setBorder(null);
        txtKBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKBarangMouseClicked(evt);
            }
        });
        txtKBarang.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtKBarangInputMethodTextChanged(evt);
            }
        });
        txtKBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKBarangActionPerformed(evt);
            }
        });
        txtKBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKBarangKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKBarangKeyTyped(evt);
            }
        });
        jPanel1.add(txtKBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 160, 30));

        txtNBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNBarang.setBorder(null);
        txtNBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNBarangKeyPressed(evt);
            }
        });
        jPanel1.add(txtNBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 150, 30));

        backtomenu.setBackground(new java.awt.Color(255, 0, 0));
        backtomenu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        backtomenu.setForeground(new java.awt.Color(255, 255, 255));
        backtomenu.setBorder(null);
        backtomenu.setContentAreaFilled(false);
        backtomenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backtomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtomenuActionPerformed(evt);
            }
        });
        jPanel1.add(backtomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        exitbtn.setBackground(new java.awt.Color(255, 0, 0));
        exitbtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setContentAreaFilled(false);
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, -1, 70));

        refreshs.setBackground(new java.awt.Color(255, 255, 0));
        refreshs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreshs.setBorder(null);
        refreshs.setContentAreaFilled(false);
        refreshs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshsActionPerformed(evt);
            }
        });
        jPanel1.add(refreshs, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 140, 50));

        btnUbah.setBackground(new java.awt.Color(255, 255, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbah.setBorder(null);
        btnUbah.setContentAreaFilled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 100, 50));

        btnHapus.setBackground(new java.awt.Color(255, 255, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setBorder(null);
        btnHapus.setContentAreaFilled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 110, 50));

        btnSimpan.setBackground(new java.awt.Color(255, 255, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setBorder(null);
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 140, 50));

        btnLapBMasuk.setBackground(new java.awt.Color(51, 51, 51));
        btnLapBMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLapBMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnLapBMasuk.setContentAreaFilled(false);
        btnLapBMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapBMasukActionPerformed(evt);
            }
        });
        jPanel1.add(btnLapBMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 300, 60));

        btnTPembelian.setBackground(new java.awt.Color(51, 51, 51));
        btnTPembelian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTPembelian.setForeground(new java.awt.Color(255, 255, 255));
        btnTPembelian.setContentAreaFilled(false);
        btnTPembelian.setFocusable(false);
        btnTPembelian.setInheritsPopupMenu(true);
        btnTPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPembelianActionPerformed(evt);
            }
        });
        jPanel1.add(btnTPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 300, 60));

        btnLapBKeluar.setBackground(new java.awt.Color(51, 51, 51));
        btnLapBKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLapBKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnLapBKeluar.setContentAreaFilled(false);
        btnLapBKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapBKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLapBKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 300, 60));

        btnDataKaryawan.setBackground(new java.awt.Color(51, 51, 51));
        btnDataKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnDataKaryawan.setContentAreaFilled(false);
        btnDataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataKaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 300, 60));

        btnTPenjualan.setBackground(new java.awt.Color(51, 51, 51));
        btnTPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnTPenjualan.setContentAreaFilled(false);
        btnTPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPenjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btnTPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, 60));

        txtSBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSBarang.setBorder(null);
        txtSBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSBarangKeyPressed(evt);
            }
        });
        jPanel1.add(txtSBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laptophp\\Documents\\NetBeansProjects\\PembukuanUMKM\\src\\images\\Data Barang mentah.png")); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1378, 767));
        jLabel1.setPreferredSize(new java.awt.Dimension(1378, 767));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1420, -1));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadtableMouseClicked
this.showData();
    }//GEN-LAST:event_loadtableMouseClicked

    private void txtKBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKBarangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKBarangMouseClicked

    private void txtKBarangInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtKBarangInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKBarangInputMethodTextChanged

    private void txtKBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKBarangActionPerformed

    private void txtKBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKBarangKeyPressed
this.kode_barangg();
    }//GEN-LAST:event_txtKBarangKeyPressed

    private void txtKBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKBarangKeyTyped
      
    }//GEN-LAST:event_txtKBarangKeyTyped

    private void txtNBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNBarangKeyPressed

    }//GEN-LAST:event_txtNBarangKeyPressed

    private void backtomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtomenuActionPerformed
        this.setVisible(false);
        new MenuUtamaKaryawan().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_backtomenuActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
       int dialogBtn = JOptionPane.YES_NO_OPTION;
int dialogResult = JOptionPane.showConfirmDialog(this,"ANDA YAKIN AKAN KELUAR?", "PERINGATAN!",dialogBtn);
  if (dialogResult == 0 ){
      System.exit(0);
  }else{
      
  }
 //        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitbtnActionPerformed

    private void refreshsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshsActionPerformed

     txtNBarang.setText("");
     txtSBarang.setText("");
          loadtable();
     kode_barangg();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshsActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String kode_barang = loadtable.getValueAt(this.loadtable.getSelectedRow(), 0).toString();

        String nama = txtNBarang.getText();
String stok = txtSBarang.getText();
        try {
            java.sql.Statement statement = Koneksi.koneksi.getKoneksi().createStatement();
            statement.executeUpdate(String.format("UPDATE data_bmentah"
                    + " SET nama_bahan = '%s',"
                    + " stok_bahan = '%s' "
                    + "WHERE id_bahan= '%s'", 
                    nama,stok,kode_barang));
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Ubah");
            kode_barangg();
            txtNBarang.setText("");
            txtSBarang.setText("");
         
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data Gagal Di Ubah"+e.getMessage());

        }
        loadtable();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

        try {
            int jawab = JOptionPane.showOptionDialog(this,
                "Ingin Hapus Data??",
                "PILIH!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

            if (jawab == JOptionPane.YES_OPTION) {
                String kode_barang = loadtable.getValueAt(this.loadtable.getSelectedRow(), 0).toString();
                java.sql.Statement statement = Koneksi.koneksi.getKoneksi().createStatement();
                statement.executeUpdate("DELETE FROM data_bmentah where id_bahan=('" + kode_barang + "');");
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus");
                kode_barangg();
                txtNBarang.setText("");
                txtSBarang.setText("");
                txtKBarang.requestFocus();

                loadtable();
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Di HAPUS");
                kode_barangg();
                txtNBarang.setText("");
                txtSBarang.setText("");
                txtKBarang.requestFocus();
                loadtable();
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
        loadtable();

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String kode = txtKBarang.getText();
        String nama = txtNBarang.getText();
        String setok = txtSBarang.getText();

        try {
            java.sql.Statement statement = Koneksi.koneksi.getKoneksi().createStatement();
            statement.executeUpdate("insert into data_bmentah VALUES ('" + kode + "','" + nama + "','" + setok + "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");

            txtNBarang.setText("");
            txtSBarang.setText("");
            txtKBarang.requestFocus();
            kode_barangg();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan\n"
                    + "Jangan iseng ya :)");
        }
        loadtable();

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitbtnMouseClicked

    private void btnLapBMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapBMasukActionPerformed
      JOptionPane.showMessageDialog(null, "MAAF\n"
           + "HANYA ADMIN YANG BISA MELIHAT MENU LAPORAN!");  // TODO add your handling code here:
    }//GEN-LAST:event_btnLapBMasukActionPerformed

    private void btnTPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPembelianActionPerformed
        this.setVisible(false);
        new TransaksiPembelianKaryawan().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnTPembelianActionPerformed

    private void btnLapBKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapBKeluarActionPerformed
          JOptionPane.showMessageDialog(null, "MAAF\n"
           + "HANYA ADMIN YANG BISA MELIHAT MENU LAPORAN!");         // TODO add your handling code here:
    }//GEN-LAST:event_btnLapBKeluarActionPerformed

    private void btnDataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataKaryawanActionPerformed
        this.setVisible(false);
        new datakariawan().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_btnDataKaryawanActionPerformed

    private void btnTPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPenjualanActionPerformed
        this.setVisible( false);
        new TransaksiPenjualanKaryawan().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnTPenjualanActionPerformed

    private void txtSBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSBarangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSBarangKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBarangKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBarangKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBarangKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBarangKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBarangKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtomenu;
    private javax.swing.JButton btnDataKaryawan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLapBKeluar;
    private javax.swing.JButton btnLapBMasuk;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTPembelian;
    private javax.swing.JButton btnTPenjualan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable loadtable;
    private javax.swing.JButton refreshs;
    private javax.swing.JTextField txtKBarang;
    private javax.swing.JTextField txtNBarang;
    private javax.swing.JTextField txtSBarang;
    // End of variables declaration//GEN-END:variables
}
