/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pembukuanumkm;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class DataKaryawan extends javax.swing.JFrame {

    public void loadtable() {
        DefaultTableModel tbl = new DefaultTableModel();

        tbl.addColumn("kode_karyawan");
        tbl.addColumn("nama_Karyawan");
        tbl.addColumn("no _Telp");
        tbl.addColumn("alamat");
        loadtable.setModel(tbl);

        try {

            java.sql.Statement statement = Koneksi.koneksi.getKoneksi().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM data_karyawan");

            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kode_karyawan"),
                    res.getString("nama_karyawan"),
                    res.getString("no_Telp"),
                    res.getString("alamat")
                });
                loadtable.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Salah");
        }

    }

    /**
     * Creates new form DataKaryawan
     */
    public DataKaryawan() {
        initComponents();
        loadtable();
        kode_karyawann();
ImageIcon icon = new ImageIcon("C:\\Users\\laptophp\\Downloads\\CIRCLE.png");
this.setIconImage(icon.getImage());
    }

    public void kode_karyawann() {
        try {
            String sql = "SELECT kode_karyawan FROM data_karyawan order by kode_karyawan desc";
            Connection conn = (Connection) Koneksi.koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            if (rs.next()) {
                String Idno = rs.getString("kode_karyawan").substring(2);
                String AN = "" + (Integer.parseInt(Idno) + 1);
                String Nol = "";
                if (AN.length() == 1) {
                    Nol = "00";
                } else if (AN.length() == 2) {
                    Nol = "0";
                } else if (AN.length() == 3) {
                    Nol = "";

                }

                txtKKaryawan.setText("K" + Nol + AN);
            } else {
                txtKKaryawan.setText("K001");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txtKKaryawan = new javax.swing.JTextField();
        txtNKaryawan = new javax.swing.JTextField();
        txtNotelp = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        backtomenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loadtable = new javax.swing.JTable();
        refreshs = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnLapBMasuk = new javax.swing.JButton();
        btnTPembelian = new javax.swing.JButton();
        btnLapBKeluar = new javax.swing.JButton();
        kembaliLogin = new javax.swing.JButton();
        btnTPenjualan = new javax.swing.JButton();
        Keluarbtn = new javax.swing.JButton();
        btnDataBarang = new javax.swing.JButton();
        btnSimpan1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKKaryawan.setEditable(false);
        txtKKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        txtKKaryawan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtKKaryawan.setBorder(null);
        txtKKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKKaryawanMouseClicked(evt);
            }
        });
        txtKKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtKKaryawanInputMethodTextChanged(evt);
            }
        });
        txtKKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKKaryawanActionPerformed(evt);
            }
        });
        txtKKaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKKaryawanKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKKaryawanKeyTyped(evt);
            }
        });
        jPanel2.add(txtKKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 190, 30));

        txtNKaryawan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNKaryawan.setBorder(null);
        txtNKaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNKaryawanKeyPressed(evt);
            }
        });
        jPanel2.add(txtNKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 200, 30));

        txtNotelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNotelp.setBorder(null);
        txtNotelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNotelpKeyPressed(evt);
            }
        });
        jPanel2.add(txtNotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 200, 20));

        txtAlamat.setBorder(null);
        jPanel2.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 200, 30));

        backtomenu.setBackground(new java.awt.Color(255, 0, 0));
        backtomenu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        backtomenu.setForeground(new java.awt.Color(255, 255, 255));
        backtomenu.setContentAreaFilled(false);
        backtomenu.setFocusable(false);
        backtomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtomenuActionPerformed(evt);
            }
        });
        jPanel2.add(backtomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 0));

        loadtable.setBorder(new javax.swing.border.MatteBorder(null));
        loadtable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Karyawan", "Nama Karyawan", "No Telpon", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        loadtable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        loadtable.setAutoscrolls(false);
        loadtable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadtable.setMinimumSize(new java.awt.Dimension(60, 500));
        loadtable.setPreferredSize(new java.awt.Dimension(300, 1020));
        loadtable.setRowHeight(30);
        loadtable.setRowMargin(2);
        loadtable.setShowGrid(false);
        loadtable.setUpdateSelectionOnSort(false);
        loadtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(loadtable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 870, 250));

        refreshs.setBackground(new java.awt.Color(255, 255, 0));
        refreshs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreshs.setContentAreaFilled(false);
        refreshs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshsActionPerformed(evt);
            }
        });
        jPanel2.add(refreshs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 360, 140, 50));

        btnUbah.setBackground(new java.awt.Color(255, 255, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbah.setContentAreaFilled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel2.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 140, 50));

        btnHapus.setBackground(new java.awt.Color(255, 255, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setContentAreaFilled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 140, 60));

        btnSimpan.setBackground(new java.awt.Color(255, 255, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 140, 60));

        btnLapBMasuk.setBackground(new java.awt.Color(51, 51, 51));
        btnLapBMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLapBMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnLapBMasuk.setContentAreaFilled(false);
        btnLapBMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapBMasukActionPerformed(evt);
            }
        });
        jPanel2.add(btnLapBMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 300, 60));

        btnTPembelian.setBackground(new java.awt.Color(51, 51, 51));
        btnTPembelian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTPembelian.setForeground(new java.awt.Color(255, 255, 255));
        btnTPembelian.setContentAreaFilled(false);
        btnTPembelian.setFocusable(false);
        btnTPembelian.setInheritsPopupMenu(true);
        btnTPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPembelianActionPerformed(evt);
            }
        });
        jPanel2.add(btnTPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 300, 60));

        btnLapBKeluar.setBackground(new java.awt.Color(51, 51, 51));
        btnLapBKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLapBKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnLapBKeluar.setContentAreaFilled(false);
        btnLapBKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapBKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLapBKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 300, 60));

        kembaliLogin.setBackground(java.awt.Color.red);
        kembaliLogin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        kembaliLogin.setForeground(new java.awt.Color(255, 255, 255));
        kembaliLogin.setContentAreaFilled(false);
        kembaliLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliLoginActionPerformed(evt);
            }
        });
        jPanel2.add(kembaliLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 60));

        btnTPenjualan.setBackground(new java.awt.Color(51, 51, 51));
        btnTPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnTPenjualan.setContentAreaFilled(false);
        btnTPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPenjualanActionPerformed(evt);
            }
        });
        jPanel2.add(btnTPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, 60));

        Keluarbtn.setBackground(java.awt.Color.red);
        Keluarbtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Keluarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Keluarbtn.setContentAreaFilled(false);
        Keluarbtn.setHideActionText(true);
        Keluarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Keluarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 80, 60));

        btnDataBarang.setBackground(new java.awt.Color(51, 51, 51));
        btnDataBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnDataBarang.setContentAreaFilled(false);
        btnDataBarang.setFocusPainted(false);
        btnDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBarangActionPerformed(evt);
            }
        });
        jPanel2.add(btnDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 300, 60));

        btnSimpan1.setBackground(new java.awt.Color(255, 255, 0));
        btnSimpan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan1.setContentAreaFilled(false);
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 140, 60));

        btnHapus1.setBackground(new java.awt.Color(255, 255, 0));
        btnHapus1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus1.setContentAreaFilled(false);
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 140, 60));

        jPanel1.setBackground(new java.awt.Color(255, 222, 47));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 170, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laptophp\\Documents\\NetBeansProjects\\PembukuanUMKM\\src\\images\\data Karyawan.png")); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1378, 767));
        jLabel1.setPreferredSize(new java.awt.Dimension(1378, 767));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1380, -1));

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKKaryawanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKKaryawanKeyPressed
        this.kode_karyawann();
    }//GEN-LAST:event_txtKKaryawanKeyPressed

    private void txtNKaryawanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNKaryawanKeyPressed

    }//GEN-LAST:event_txtNKaryawanKeyPressed

    private void showData() {
        try {
            String kode_karyawan = loadtable.getValueAt(this.loadtable.getSelectedRow(), 0).toString();
            Connection conn = (Connection) Koneksi.koneksi.getKoneksi();
            Statement s = conn.createStatement();
            ResultSet r = s.executeQuery("SELECT kode_karyawan, nama_karyawan, no_telp, alamat FROM data_karyawan WHERE kode_karyawan = '" + kode_karyawan + "'");
            if (r.next()) {

                this.txtKKaryawan.setText(r.getString("kode_karyawan"));
                this.txtNKaryawan.setText(r.getString("nama_karyawan"));
                this.txtNotelp.setText(r.getString("no_telp"));
                this.txtAlamat.setText(r.getString("alamat"));
            }

        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }

    private void loadtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadtableMouseClicked
        this.showData();
    }//GEN-LAST:event_loadtableMouseClicked

    private void txtNotelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotelpKeyPressed

    }//GEN-LAST:event_txtNotelpKeyPressed

    private void backtomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtomenuActionPerformed
        dispose();
        new MenuUtama().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_backtomenuActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String kode_karyawan = loadtable.getValueAt(this.loadtable.getSelectedRow(), 0).toString();
        String nama = txtNKaryawan.getText();
        String notelp = txtNotelp.getText();
        String alamat = txtAlamat.getText();

        try {
            java.sql.Statement statement = Koneksi.koneksi.getKoneksi().createStatement();
            statement.executeUpdate(String.format("UPDATE data_karyawan SET nama_karyawan = '%s', no_telp = '%s', alamat = '%s' WHERE kode_karyawan = '%s'", nama, notelp, alamat, kode_karyawan));
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Ubah");
            kode_karyawann();
            txtNKaryawan.setText("");
            txtNotelp.setText("");
            txtAlamat.setText("");
            txtKKaryawan.requestFocus();
//            if()
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data Gagal Di Ubah");

        }
        loadtable();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

        try {
            int jawab = JOptionPane.showOptionDialog(this,
                    "Ingin Hapus Data??",
                    "PILIH!",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, null, null);

            if (jawab == JOptionPane.YES_OPTION) {
                String kode_karyawan = loadtable.getValueAt(this.loadtable.getSelectedRow(), 0).toString();
                java.sql.Statement statement = Koneksi.koneksi.getKoneksi().createStatement();
                statement.executeUpdate("DELETE FROM data_karyawan where kode_Karyawan=('" + kode_karyawan + "');");
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus");
                kode_karyawann();
                txtNKaryawan.setText("");
                txtNotelp.setText("");
                txtAlamat.setText("");
                txtKKaryawan.requestFocus();

                loadtable();
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Di HAPUS");
                kode_karyawann();
                txtNKaryawan.setText("");
                txtNotelp.setText("");
                txtAlamat.setText("");
                txtKKaryawan.requestFocus();
                loadtable();
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
        loadtable();


    }//GEN-LAST:event_btnHapusActionPerformed


    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String kode = txtKKaryawan.getText();
        String nama = txtNKaryawan.getText();
        String notelp = txtNotelp.getText();
        String alamat = txtAlamat.getText();

        try {
            java.sql.Statement statement = Koneksi.koneksi.getKoneksi().createStatement();
            statement.executeUpdate("insert into data_karyawan VALUES ('" + kode + "','" + nama + "','" + notelp + "','" + alamat + "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");

            txtNKaryawan.setText("");
            txtNotelp.setText("");
            txtAlamat.setText("");
            txtKKaryawan.requestFocus();
            kode_karyawann();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan\n"
                    + "Jangan iseng dong -_-");
        }
        loadtable();

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void refreshsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshsActionPerformed

        txtNKaryawan.setText("");
        txtNotelp.setText("");
        txtAlamat.setText("");
        kode_karyawann();
        loadtable();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshsActionPerformed


    private void txtKKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKKaryawanActionPerformed

    private void txtKKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtKKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKKaryawanInputMethodTextChanged

    private void txtKKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKKaryawanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKKaryawanMouseClicked

    private void txtKKaryawanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKKaryawanKeyTyped
        this.kode_karyawann();        // TODO add your handling code here:
    }//GEN-LAST:event_txtKKaryawanKeyTyped

    private void btnLapBMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapBMasukActionPerformed
  dispose();
        new LaporanBarangMasuk().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLapBMasukActionPerformed

    private void btnTPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPembelianActionPerformed
      dispose();
        new TransaksiPembelian().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnTPembelianActionPerformed

    private void btnLapBKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapBKeluarActionPerformed
        dispose();
        new LaporanBarangKeluar().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_btnLapBKeluarActionPerformed

    private void kembaliLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliLoginActionPerformed
       dispose();
        new LoginUser().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliLoginActionPerformed

    private void btnTPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPenjualanActionPerformed
       dispose();
        new TransaksiPenjualan().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnTPenjualanActionPerformed

    private void KeluarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarbtnActionPerformed
            int dialogBtn = JOptionPane.YES_NO_OPTION;
int dialogResult = JOptionPane.showConfirmDialog(this,"ANDA YAKIN AKAN KELUAR?", "PERINGATAN!",dialogBtn);
  if (dialogResult == 0 ){
      System.exit(0);
  }else{
      
  }
        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarbtnActionPerformed

    private void btnDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBarangActionPerformed
        dispose();
        new DataBarang().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataBarangActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapus1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKaryawan().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluarbtn;
    private javax.swing.JButton backtomenu;
    private javax.swing.JButton btnDataBarang;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnLapBKeluar;
    private javax.swing.JButton btnLapBMasuk;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JButton btnTPembelian;
    private javax.swing.JButton btnTPenjualan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembaliLogin;
    private javax.swing.JTable loadtable;
    private javax.swing.JButton refreshs;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtKKaryawan;
    private javax.swing.JTextField txtNKaryawan;
    private javax.swing.JTextField txtNotelp;
    // End of variables declaration//GEN-END:variables
}
